apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: monolith-1
  description: Monolith 1
  annotations:
    github.com/project-slug: gobriango19/monolith-1
spec:
  type: website
  lifecycle: "random status"
  owner: brian
  dependsOn:
    - component:monolith-1-component-1
    - component:monolith-1-component-2
    - component:monolith-1-component-3
---
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: monolith-1-components-locations
spec:
  targets:
    - ./monolith-1-component-1/backstage.yaml
    - ./monolith-1-component-2/backstage.yaml
    - ./monolith-1-component-3/backstage.yaml